flowchart LR
  n_92uRnWJbhgCsGvkbSWAY_12["rst"]
  n_92uRnWJbhgCsGvkbSWAY_14["clk"]
  n_92uRnWJbhgCsGvkbSWAY_16["clk_div_100kHz"]
  n_92uRnWJbhgCsGvkbSWAY_17["node_WAY-17"]
  n_92uRnWJbhgCsGvkbSWAY_19["clk"]
  n_92uRnWJbhgCsGvkbSWAY_21["rst"]
  n_92uRnWJbhgCsGvkbSWAY_22["node_WAY-22"]
  n_92uRnWJbhgCsGvkbSWAY_23["node_WAY-23"]
  n_92uRnWJbhgCsGvkbSWAY_25["clk_100kHz"]
  n_92uRnWJbhgCsGvkbSWAY_27["shift_reg[7:0"]
  n_92uRnWJbhgCsGvkbSWAY_28["node_WAY-28"]
  n_92uRnWJbhgCsGvkbSWAY_38["node_WAY-38"]
  n_92uRnWJbhgCsGvkbSWAY_39["d_ff"]
  n_92uRnWJbhgCsGvkbSWAY_43["clk"]
  n_92uRnWJbhgCsGvkbSWAY_44["node_WAY-44"]
  n_92uRnWJbhgCsGvkbSWAY_46["w_debouncer"]
  n_92uRnWJbhgCsGvkbSWAY_53["node_WAY-53"]
  n_92uRnWJbhgCsGvkbSWAY_57["node_WAY-57"]
  n_92uRnWJbhgCsGvkbSWAY_59["i_btn"]
  n_92uRnWJbhgCsGvkbSWAY_61["1s_count_tick"]
  n_92uRnWJbhgCsGvkbSWAY_63["clk"]
  n_92uRnWJbhgCsGvkbSWAY_64["node_WAY-64"]
  n_92uRnWJbhgCsGvkbSWAY_70["o_btn_hold"]
  n_92uRnWJbhgCsGvkbSWAY_71["o_btn"]
  n_92uRnWJbhgCsGvkbSWAY_75["rst"]
  n_92uRnWJbhgCsGvkbSWAY_77["rst"]
  n_92uRnWJbhgCsGvkbSWAY_8["node_SWAY-8"]
  n_92uRnWJbhgCsGvkbSWAY_81["rst"]
  n_92uRnWJbhgCsGvkbSWAY_28 --> n_92uRnWJbhgCsGvkbSWAY_39
