flowchart LR
  n_E9N4p9MdtPNkOz_vh_yI_1["node_h_yI-1"]
  n_Xt5h5PVO_5MyDHxTXsWM_1["node_XsWM-1"]
  n_Xt5h5PVO_5MyDHxTXsWM_10["6"]
  n_Xt5h5PVO_5MyDHxTXsWM_11["sec_tick_count"]
  n_Xt5h5PVO_5MyDHxTXsWM_13["o_sec_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_14["i_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_18["min_tick_count"]
  n_Xt5h5PVO_5MyDHxTXsWM_2["timepiecer_datapath"]
  n_Xt5h5PVO_5MyDHxTXsWM_20["5"]
  n_Xt5h5PVO_5MyDHxTXsWM_21["hour_tick_count"]
  n_Xt5h5PVO_5MyDHxTXsWM_22["o_hour_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_23["i_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_24["o_min_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_25["i_tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_27["i_set_index"]
  n_Xt5h5PVO_5MyDHxTXsWM_29["i_set_mode"]
  n_Xt5h5PVO_5MyDHxTXsWM_31["i_index_shift"]
  n_Xt5h5PVO_5MyDHxTXsWM_33["i_decrement"]
  n_Xt5h5PVO_5MyDHxTXsWM_38["time_set_module"]
  n_Xt5h5PVO_5MyDHxTXsWM_4["100Hz tick"]
  n_Xt5h5PVO_5MyDHxTXsWM_40["i_increment"]
  n_Xt5h5PVO_5MyDHxTXsWM_42["24"]
  n_Xt5h5PVO_5MyDHxTXsWM_44["w_set_msec"]
  n_Xt5h5PVO_5MyDHxTXsWM_46["w_set_sec"]
  n_Xt5h5PVO_5MyDHxTXsWM_48["w_set_min"]
  n_Xt5h5PVO_5MyDHxTXsWM_5["tick_gen _100hz"]
  n_Xt5h5PVO_5MyDHxTXsWM_50["w_set_hour"]
  n_Xt5h5PVO_5MyDHxTXsWM_55["w_set_mode"]
  n_Xt5h5PVO_5MyDHxTXsWM_56["w_timepiiecer_value"]
  n_Xt5h5PVO_5MyDHxTXsWM_58["24"]
  n_Xt5h5PVO_5MyDHxTXsWM_59["o_timepiecer_value"]
  n_Xt5h5PVO_5MyDHxTXsWM_61["i_decrement_1s"]
  n_Xt5h5PVO_5MyDHxTXsWM_63["i_increment_1s"]
  n_Xt5h5PVO_5MyDHxTXsWM_67["clk"]
  n_Xt5h5PVO_5MyDHxTXsWM_7["7"]
  n_Xt5h5PVO_5MyDHxTXsWM_71["rst"]
  n_Xt5h5PVO_5MyDHxTXsWM_8["msec_tick_count"]
  n_Xt5h5PVO_5MyDHxTXsWM_8 --> n_Xt5h5PVO_5MyDHxTXsWM_11
  n_Xt5h5PVO_5MyDHxTXsWM_11 --> n_Xt5h5PVO_5MyDHxTXsWM_18
  n_Xt5h5PVO_5MyDHxTXsWM_18 --> n_Xt5h5PVO_5MyDHxTXsWM_21
