flowchart LR
  n_UGjPlsAckatZPpFdG2PR_1["IDEL"]
  n_UGjPlsAckatZPpFdG2PR_11["START"]
  n_UGjPlsAckatZPpFdG2PR_119["baut_tick == 1"]
  n_UGjPlsAckatZPpFdG2PR_120["F"]
  n_UGjPlsAckatZPpFdG2PR_121["T"]
  n_UGjPlsAckatZPpFdG2PR_125["WAIT"]
  n_UGjPlsAckatZPpFdG2PR_129["baut_tick == 1"]
  n_UGjPlsAckatZPpFdG2PR_13["T"]
  n_UGjPlsAckatZPpFdG2PR_134["baut_tick == 1"]
  n_UGjPlsAckatZPpFdG2PR_135["baut_tick == 1"]
  n_UGjPlsAckatZPpFdG2PR_2["start == 1"]
  n_UGjPlsAckatZPpFdG2PR_34["TX = 0"]
  n_UGjPlsAckatZPpFdG2PR_36["bit0"]
  n_UGjPlsAckatZPpFdG2PR_38["TX = data[0]"]
  n_UGjPlsAckatZPpFdG2PR_41["START"]
  n_UGjPlsAckatZPpFdG2PR_5["TX = 1"]
  n_UGjPlsAckatZPpFdG2PR_7["IDLE"]
  n_UGjPlsAckatZPpFdG2PR_81["bit2"]
  n_UGjPlsAckatZPpFdG2PR_82["TX = data[2]"]
  n_UGjPlsAckatZPpFdG2PR_9["F"]
  n_UGjPlsAckatZPpFdG2PR_98["STOP"]
  n_lQCQZTKk_LeILsxmWH9y_11["START"]
  n_lQCQZTKk_LeILsxmWH9y_12["T"]
  n_lQCQZTKk_LeILsxmWH9y_14["TX = 0"]
  n_lQCQZTKk_LeILsxmWH9y_15["START"]
  n_lQCQZTKk_LeILsxmWH9y_17["baut_tick == 1"]
  n_lQCQZTKk_LeILsxmWH9y_19["F"]
  n_lQCQZTKk_LeILsxmWH9y_2["IDLE"]
  n_lQCQZTKk_LeILsxmWH9y_20["T"]
  n_lQCQZTKk_LeILsxmWH9y_22["WAIT"]
  n_lQCQZTKk_LeILsxmWH9y_24["baut_tick == 1"]
  n_lQCQZTKk_LeILsxmWH9y_25["F"]
  n_lQCQZTKk_LeILsxmWH9y_26["T"]
  n_lQCQZTKk_LeILsxmWH9y_27["DATA_TX"]
  n_lQCQZTKk_LeILsxmWH9y_30["TX = data[count]"]
  n_lQCQZTKk_LeILsxmWH9y_31["baut_tick == 1"]
  n_lQCQZTKk_LeILsxmWH9y_33["count == 7"]
  n_lQCQZTKk_LeILsxmWH9y_35["STOP"]
  n_lQCQZTKk_LeILsxmWH9y_5["start == 1"]
  n_lQCQZTKk_LeILsxmWH9y_7["TX = 1"]
  n_lQCQZTKk_LeILsxmWH9y_8["IDLE"]
  n_lQCQZTKk_LeILsxmWH9y_9["F"]
  n_o1f4UlkyCeSKwryDGnv5_1["baut_tick == 1"]
  n_o1f4UlkyCeSKwryDGnv5_12["F"]
  n_o1f4UlkyCeSKwryDGnv5_4["T"]
  n_o1f4UlkyCeSKwryDGnv5_5["T"]
  n_o1f4UlkyCeSKwryDGnv5_6["T"]
  n_o1f4UlkyCeSKwryDGnv5_7["F"]
  n_o1f4UlkyCeSKwryDGnv5_9["F"]
  n_z6RQsE05kwIORvhBAqgg_11["bit4"]
  n_z6RQsE05kwIORvhBAqgg_12["TX = data[4]"]
  n_z6RQsE05kwIORvhBAqgg_13["bit6"]
  n_z6RQsE05kwIORvhBAqgg_14["TX = data[6]"]
  n_z6RQsE05kwIORvhBAqgg_15["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_16["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_18["bit5"]
  n_z6RQsE05kwIORvhBAqgg_19["TX = data[5]"]
  n_z6RQsE05kwIORvhBAqgg_20["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_21["bit7"]
  n_z6RQsE05kwIORvhBAqgg_22["TX = data[7]"]
  n_z6RQsE05kwIORvhBAqgg_23["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_4["bit1"]
  n_z6RQsE05kwIORvhBAqgg_42["F"]
  n_z6RQsE05kwIORvhBAqgg_43["T"]
  n_z6RQsE05kwIORvhBAqgg_44["T"]
  n_z6RQsE05kwIORvhBAqgg_45["T"]
  n_z6RQsE05kwIORvhBAqgg_46["T"]
  n_z6RQsE05kwIORvhBAqgg_47["T"]
  n_z6RQsE05kwIORvhBAqgg_48["T"]
  n_z6RQsE05kwIORvhBAqgg_49["T"]
  n_z6RQsE05kwIORvhBAqgg_5["TX = data[1]"]
  n_z6RQsE05kwIORvhBAqgg_51["T"]
  n_z6RQsE05kwIORvhBAqgg_52["T"]
  n_z6RQsE05kwIORvhBAqgg_6["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_64["F"]
  n_z6RQsE05kwIORvhBAqgg_65["F"]
  n_z6RQsE05kwIORvhBAqgg_66["F"]
  n_z6RQsE05kwIORvhBAqgg_67["F"]
  n_z6RQsE05kwIORvhBAqgg_68["F"]
  n_z6RQsE05kwIORvhBAqgg_69["F"]
  n_z6RQsE05kwIORvhBAqgg_7["bit3"]
  n_z6RQsE05kwIORvhBAqgg_70["F"]
  n_z6RQsE05kwIORvhBAqgg_71["F"]
  n_z6RQsE05kwIORvhBAqgg_73["TX = 1"]
  n_z6RQsE05kwIORvhBAqgg_77["baut_tick == 1"]
  n_z6RQsE05kwIORvhBAqgg_79["T"]
  n_z6RQsE05kwIORvhBAqgg_8["TX = data[3]"]
  n_z6RQsE05kwIORvhBAqgg_81["F"]
  n_z6RQsE05kwIORvhBAqgg_9["baut_tick == 1"]
  n_UGjPlsAckatZPpFdG2PR_1 --> n_UGjPlsAckatZPpFdG2PR_5
  n_UGjPlsAckatZPpFdG2PR_2 --> n_UGjPlsAckatZPpFdG2PR_1
  n_UGjPlsAckatZPpFdG2PR_2 --> n_UGjPlsAckatZPpFdG2PR_125
  n_UGjPlsAckatZPpFdG2PR_5 --> n_UGjPlsAckatZPpFdG2PR_2
  n_UGjPlsAckatZPpFdG2PR_11 --> n_UGjPlsAckatZPpFdG2PR_34
  n_UGjPlsAckatZPpFdG2PR_36 --> n_UGjPlsAckatZPpFdG2PR_38
  n_UGjPlsAckatZPpFdG2PR_38 --> n_UGjPlsAckatZPpFdG2PR_134
  n_UGjPlsAckatZPpFdG2PR_81 --> n_UGjPlsAckatZPpFdG2PR_82
  n_UGjPlsAckatZPpFdG2PR_82 --> n_UGjPlsAckatZPpFdG2PR_135
  n_UGjPlsAckatZPpFdG2PR_98 --> n_z6RQsE05kwIORvhBAqgg_73
  n_UGjPlsAckatZPpFdG2PR_119 --> n_UGjPlsAckatZPpFdG2PR_125
  n_UGjPlsAckatZPpFdG2PR_125 --> n_UGjPlsAckatZPpFdG2PR_119
  n_UGjPlsAckatZPpFdG2PR_129 --> n_UGjPlsAckatZPpFdG2PR_36
  n_UGjPlsAckatZPpFdG2PR_129 --> n_UGjPlsAckatZPpFdG2PR_11
  n_UGjPlsAckatZPpFdG2PR_134 --> n_z6RQsE05kwIORvhBAqgg_4
  n_UGjPlsAckatZPpFdG2PR_134 --> n_UGjPlsAckatZPpFdG2PR_36
  n_UGjPlsAckatZPpFdG2PR_135 --> n_z6RQsE05kwIORvhBAqgg_7
  n_UGjPlsAckatZPpFdG2PR_135 --> n_UGjPlsAckatZPpFdG2PR_81
  n_z6RQsE05kwIORvhBAqgg_4 --> n_z6RQsE05kwIORvhBAqgg_5
  n_z6RQsE05kwIORvhBAqgg_5 --> n_z6RQsE05kwIORvhBAqgg_6
  n_z6RQsE05kwIORvhBAqgg_6 --> n_UGjPlsAckatZPpFdG2PR_81
  n_z6RQsE05kwIORvhBAqgg_6 --> n_z6RQsE05kwIORvhBAqgg_4
  n_z6RQsE05kwIORvhBAqgg_7 --> n_z6RQsE05kwIORvhBAqgg_8
  n_z6RQsE05kwIORvhBAqgg_8 --> n_z6RQsE05kwIORvhBAqgg_9
  n_z6RQsE05kwIORvhBAqgg_9 --> n_z6RQsE05kwIORvhBAqgg_11
  n_z6RQsE05kwIORvhBAqgg_9 --> n_z6RQsE05kwIORvhBAqgg_7
  n_z6RQsE05kwIORvhBAqgg_11 --> n_z6RQsE05kwIORvhBAqgg_12
  n_z6RQsE05kwIORvhBAqgg_12 --> n_z6RQsE05kwIORvhBAqgg_15
  n_z6RQsE05kwIORvhBAqgg_13 --> n_z6RQsE05kwIORvhBAqgg_14
  n_z6RQsE05kwIORvhBAqgg_14 --> n_z6RQsE05kwIORvhBAqgg_16
  n_z6RQsE05kwIORvhBAqgg_15 --> n_z6RQsE05kwIORvhBAqgg_18
  n_z6RQsE05kwIORvhBAqgg_15 --> n_z6RQsE05kwIORvhBAqgg_11
  n_z6RQsE05kwIORvhBAqgg_16 --> n_z6RQsE05kwIORvhBAqgg_21
  n_z6RQsE05kwIORvhBAqgg_16 --> n_z6RQsE05kwIORvhBAqgg_13
  n_z6RQsE05kwIORvhBAqgg_18 --> n_z6RQsE05kwIORvhBAqgg_19
  n_z6RQsE05kwIORvhBAqgg_19 --> n_z6RQsE05kwIORvhBAqgg_20
  n_z6RQsE05kwIORvhBAqgg_20 --> n_z6RQsE05kwIORvhBAqgg_13
  n_z6RQsE05kwIORvhBAqgg_20 --> n_z6RQsE05kwIORvhBAqgg_18
  n_z6RQsE05kwIORvhBAqgg_21 --> n_z6RQsE05kwIORvhBAqgg_22
  n_z6RQsE05kwIORvhBAqgg_22 --> n_z6RQsE05kwIORvhBAqgg_23
  n_z6RQsE05kwIORvhBAqgg_23 --> n_z6RQsE05kwIORvhBAqgg_21
  n_z6RQsE05kwIORvhBAqgg_23 --> n_UGjPlsAckatZPpFdG2PR_98
  n_z6RQsE05kwIORvhBAqgg_77 --> n_UGjPlsAckatZPpFdG2PR_1
  n_z6RQsE05kwIORvhBAqgg_77 --> n_UGjPlsAckatZPpFdG2PR_98
  n_lQCQZTKk_LeILsxmWH9y_2 --> n_lQCQZTKk_LeILsxmWH9y_7
  n_lQCQZTKk_LeILsxmWH9y_5 --> n_lQCQZTKk_LeILsxmWH9y_2
  n_lQCQZTKk_LeILsxmWH9y_5 --> n_lQCQZTKk_LeILsxmWH9y_22
  n_lQCQZTKk_LeILsxmWH9y_7 --> n_lQCQZTKk_LeILsxmWH9y_5
  n_lQCQZTKk_LeILsxmWH9y_11 --> n_lQCQZTKk_LeILsxmWH9y_14
  n_lQCQZTKk_LeILsxmWH9y_17 --> n_lQCQZTKk_LeILsxmWH9y_22
  n_lQCQZTKk_LeILsxmWH9y_22 --> n_lQCQZTKk_LeILsxmWH9y_17
  n_lQCQZTKk_LeILsxmWH9y_24 --> n_lQCQZTKk_LeILsxmWH9y_11
  n_lQCQZTKk_LeILsxmWH9y_24 --> n_lQCQZTKk_LeILsxmWH9y_27
  n_lQCQZTKk_LeILsxmWH9y_27 --> n_lQCQZTKk_LeILsxmWH9y_30
  n_lQCQZTKk_LeILsxmWH9y_30 --> n_lQCQZTKk_LeILsxmWH9y_31
  n_lQCQZTKk_LeILsxmWH9y_31 --> n_lQCQZTKk_LeILsxmWH9y_33
  n_lQCQZTKk_LeILsxmWH9y_33 --> n_lQCQZTKk_LeILsxmWH9y_27
  n_lQCQZTKk_LeILsxmWH9y_33 --> n_lQCQZTKk_LeILsxmWH9y_35
  n_lQCQZTKk_LeILsxmWH9y_35 --> n_o1f4UlkyCeSKwryDGnv5_1
  n_o1f4UlkyCeSKwryDGnv5_1 --> n_lQCQZTKk_LeILsxmWH9y_2
  n_o1f4UlkyCeSKwryDGnv5_1 --> n_lQCQZTKk_LeILsxmWH9y_35
  n_lQCQZTKk_LeILsxmWH9y_31 --> n_lQCQZTKk_LeILsxmWH9y_27
