flowchart LR
  n_t1mIC5yygEkDqqAOm0CT_10["b[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_14["w_sum[3:0]<br/>(bin[3:0])"]
  n_t1mIC5yygEkDqqAOm0CT_16["led"]
  n_t1mIC5yygEkDqqAOm0CT_18["carry"]
  n_t1mIC5yygEkDqqAOm0CT_19["fnd_data[7:0]"]
  n_t1mIC5yygEkDqqAOm0CT_2["adder_fnd Block Diagram"]
  n_t1mIC5yygEkDqqAOm0CT_22["fnd_com[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_25["(7-Segment Lines)"]
  n_t1mIC5yygEkDqqAOm0CT_26["(Digit Select)"]
  n_t1mIC5yygEkDqqAOm0CT_27["(Carry Out)"]
  n_t1mIC5yygEkDqqAOm0CT_28["a[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_29["b[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_3["node_m0CT-3"]
  n_t1mIC5yygEkDqqAOm0CT_30["sum[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_31["carry"]
  n_t1mIC5yygEkDqqAOm0CT_32["bin[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_33["INPUTS"]
  n_t1mIC5yygEkDqqAOm0CT_34["OUTPUTS"]
  n_t1mIC5yygEkDqqAOm0CT_36["fnd_com[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_38["fnd_data[7:0]"]
  n_t1mIC5yygEkDqqAOm0CT_4["adder_fnd"]
  n_t1mIC5yygEkDqqAOm0CT_5["full_adder_4bit<br/>4-bit Full Adder"]
  n_t1mIC5yygEkDqqAOm0CT_6["fnd_controller<br/>4-bit to 7-Segment<br/>Display Controller"]
  n_t1mIC5yygEkDqqAOm0CT_7["a[3:0]"]
  n_t1mIC5yygEkDqqAOm0CT_7 --> n_t1mIC5yygEkDqqAOm0CT_28
  n_t1mIC5yygEkDqqAOm0CT_10 --> n_t1mIC5yygEkDqqAOm0CT_29
  n_t1mIC5yygEkDqqAOm0CT_30 --> n_t1mIC5yygEkDqqAOm0CT_6
  n_t1mIC5yygEkDqqAOm0CT_31 --> n_t1mIC5yygEkDqqAOm0CT_16
