flowchart LR
  n_b8cbeCLrpgBhF2lM7fum_36["node_fum-36"]
  n_b8cbeCLrpgBhF2lM7fum_40["i_clear"]
  n_b8cbeCLrpgBhF2lM7fum_41["i_updown"]
  n_b8cbeCLrpgBhF2lM7fum_42["i_runstop"]
  n_b8cbeCLrpgBhF2lM7fum_43["timer_datapath"]
  n_b8cbeCLrpgBhF2lM7fum_45["100Hz tick"]
  n_b8cbeCLrpgBhF2lM7fum_46["tick_gen _100hz"]
  n_b8cbeCLrpgBhF2lM7fum_48["7"]
  n_b8cbeCLrpgBhF2lM7fum_49["msec_tick_count"]
  n_b8cbeCLrpgBhF2lM7fum_51["6"]
  n_b8cbeCLrpgBhF2lM7fum_52["sec_tick_count"]
  n_b8cbeCLrpgBhF2lM7fum_54["o_sec_tick"]
  n_b8cbeCLrpgBhF2lM7fum_55["i_tick"]
  n_b8cbeCLrpgBhF2lM7fum_59["min_tick_count"]
  n_b8cbeCLrpgBhF2lM7fum_61["5"]
  n_b8cbeCLrpgBhF2lM7fum_62["hour_tink_count"]
  n_b8cbeCLrpgBhF2lM7fum_63["o_hour_tick"]
  n_b8cbeCLrpgBhF2lM7fum_64["i_tick"]
  n_b8cbeCLrpgBhF2lM7fum_65["o_min_tick"]
  n_b8cbeCLrpgBhF2lM7fum_66["i_tick"]
  n_b8cbeCLrpgBhF2lM7fum_68["24"]
  n_b8cbeCLrpgBhF2lM7fum_69["o_timer_value"]
  n_b8cbeCLrpgBhF2lM7fum_75["rst"]
  n_b8cbeCLrpgBhF2lM7fum_76["clk"]
  n_b8cbeCLrpgBhF2lM7fum_77["node_fum-77"]
  n_c6urQ4iPjfcKnkznKz9D_2["clk"]
  n_c6urQ4iPjfcKnkznKz9D_3["node_Kz9D-3"]
  n_c6urQ4iPjfcKnkznKz9D_5["rst"]
  n_b8cbeCLrpgBhF2lM7fum_49 --> n_b8cbeCLrpgBhF2lM7fum_52
  n_b8cbeCLrpgBhF2lM7fum_52 --> n_b8cbeCLrpgBhF2lM7fum_59
  n_b8cbeCLrpgBhF2lM7fum_59 --> n_b8cbeCLrpgBhF2lM7fum_62
