flowchart LR
  n_g0RLNKt16P9XedoZUAFf_1["timepiece_fsm"]
  n_g0RLNKt16P9XedoZUAFf_17["i_btnL"]
  n_g0RLNKt16P9XedoZUAFf_18["i_btnU"]
  n_g0RLNKt16P9XedoZUAFf_19["i_btnU_hold"]
  n_g0RLNKt16P9XedoZUAFf_20["i_btnD"]
  n_g0RLNKt16P9XedoZUAFf_21["i_btnD_hold"]
  n_g0RLNKt16P9XedoZUAFf_25["i_sw0"]
  n_g0RLNKt16P9XedoZUAFf_27["o_set_index"]
  n_g0RLNKt16P9XedoZUAFf_29["o_set_mode"]
  n_g0RLNKt16P9XedoZUAFf_31["o_index_shift"]
  n_g0RLNKt16P9XedoZUAFf_33["o_decrement_ones"]
  n_g0RLNKt16P9XedoZUAFf_35["o_increment_ones"]
  n_g0RLNKt16P9XedoZUAFf_38["clk"]
  n_g0RLNKt16P9XedoZUAFf_39["rst"]
  n_g0RLNKt16P9XedoZUAFf_40["node_AFf-40"]
  n_g0RLNKt16P9XedoZUAFf_44["o_decrement_tens"]
  n_g0RLNKt16P9XedoZUAFf_46["o_increment_tens"]
