flowchart LR
  n_rImcKjZK05_8i4gp4gPj_1["4"]
  n_wnviPB3tqa4_CWSCMsV8_2["comparator"]
  n_wnviPB3tqa4_CWSCMsV8_5["2Hz"]
  n_zSLJHqy5dTzYmLFUhb4U_10["conter_8"]
  n_zSLJHqy5dTzYmLFUhb4U_11["decoder_2x4"]
  n_zSLJHqy5dTzYmLFUhb4U_12["msec DS"]
  n_zSLJHqy5dTzYmLFUhb4U_13["sec DS"]
  n_zSLJHqy5dTzYmLFUhb4U_22["node_b4U-22"]
  n_zSLJHqy5dTzYmLFUhb4U_23["msec DS"]
  n_zSLJHqy5dTzYmLFUhb4U_25["sec DS"]
  n_zSLJHqy5dTzYmLFUhb4U_30["dot_index_controller(mux)"]
  n_zSLJHqy5dTzYmLFUhb4U_44["4'hf"]
  n_zSLJHqy5dTzYmLFUhb4U_45["4'hf"]
  n_zSLJHqy5dTzYmLFUhb4U_47["4'hf"]
  n_zSLJHqy5dTzYmLFUhb4U_49["4'hf"]
  n_zSLJHqy5dTzYmLFUhb4U_61["node_b4U-61"]
  n_zSLJHqy5dTzYmLFUhb4U_64["0"]
  n_zSLJHqy5dTzYmLFUhb4U_65["1"]
  n_zSLJHqy5dTzYmLFUhb4U_66["4"]
  n_zSLJHqy5dTzYmLFUhb4U_67["4"]
  n_zSLJHqy5dTzYmLFUhb4U_68["BCD"]
  n_zSLJHqy5dTzYmLFUhb4U_74["i_display_mode"]
  n_zSLJHqy5dTzYmLFUhb4U_77["node_b4U-77"]
  n_zSLJHqy5dTzYmLFUhb4U_78["node_b4U-78"]
  n_zSLJHqy5dTzYmLFUhb4U_79["node_b4U-79"]
  n_zSLJHqy5dTzYmLFUhb4U_8["node_hb4U-8"]
  n_zSLJHqy5dTzYmLFUhb4U_80["node_b4U-80"]
  n_zSLJHqy5dTzYmLFUhb4U_81["node_b4U-81"]
  n_zSLJHqy5dTzYmLFUhb4U_83["8"]
  n_zSLJHqy5dTzYmLFUhb4U_85["4"]
  n_zSLJHqy5dTzYmLFUhb4U_86["node_b4U-86"]
  n_zSLJHqy5dTzYmLFUhb4U_87["i_display_value"]
  n_zSLJHqy5dTzYmLFUhb4U_93["i_set_index"]
  n_zSLJHqy5dTzYmLFUhb4U_95["mux1"]
  n_zSLJHqy5dTzYmLFUhb4U_96["mux1"]
  n_zSLJHqy5dTzYmLFUhb4U_97["3"]
  n_zSLJHqy5dTzYmLFUhb4U_98["fnd_controller"]
  n_zSLJHqy5dTzYmLFUhb4U_61 --> n_zSLJHqy5dTzYmLFUhb4U_68
  n_zSLJHqy5dTzYmLFUhb4U_8 --> n_zSLJHqy5dTzYmLFUhb4U_61
  n_zSLJHqy5dTzYmLFUhb4U_10 --> n_zSLJHqy5dTzYmLFUhb4U_11
  n_zSLJHqy5dTzYmLFUhb4U_11 --> n_zSLJHqy5dTzYmLFUhb4U_77
  n_zSLJHqy5dTzYmLFUhb4U_13 --> n_zSLJHqy5dTzYmLFUhb4U_8
  n_zSLJHqy5dTzYmLFUhb4U_12 --> n_zSLJHqy5dTzYmLFUhb4U_8
  n_zSLJHqy5dTzYmLFUhb4U_12 --> n_zSLJHqy5dTzYmLFUhb4U_8
  n_zSLJHqy5dTzYmLFUhb4U_13 --> n_zSLJHqy5dTzYmLFUhb4U_8
  n_zSLJHqy5dTzYmLFUhb4U_22 --> n_zSLJHqy5dTzYmLFUhb4U_61
  n_zSLJHqy5dTzYmLFUhb4U_25 --> n_zSLJHqy5dTzYmLFUhb4U_22
  n_zSLJHqy5dTzYmLFUhb4U_23 --> n_zSLJHqy5dTzYmLFUhb4U_22
  n_zSLJHqy5dTzYmLFUhb4U_23 --> n_zSLJHqy5dTzYmLFUhb4U_22
  n_zSLJHqy5dTzYmLFUhb4U_25 --> n_zSLJHqy5dTzYmLFUhb4U_22
  n_zSLJHqy5dTzYmLFUhb4U_68 --> n_zSLJHqy5dTzYmLFUhb4U_77
  n_zSLJHqy5dTzYmLFUhb4U_74 --> n_zSLJHqy5dTzYmLFUhb4U_61
  n_zSLJHqy5dTzYmLFUhb4U_87 --> n_zSLJHqy5dTzYmLFUhb4U_25
  n_zSLJHqy5dTzYmLFUhb4U_93 --> n_zSLJHqy5dTzYmLFUhb4U_30
  n_wnviPB3tqa4_CWSCMsV8_2 --> n_zSLJHqy5dTzYmLFUhb4U_30
