flowchart LR
  n_TjsLkfRK9ERH6KQQvVYx_1["node_vVYx-1"]
  n_TjsLkfRK9ERH6KQQvVYx_10["stopwatch_payload"]
  n_TjsLkfRK9ERH6KQQvVYx_13["watch_payload"]
  n_TjsLkfRK9ERH6KQQvVYx_14["sr04_payload"]
  n_TjsLkfRK9ERH6KQQvVYx_18["dht11_payload"]
  n_TjsLkfRK9ERH6KQQvVYx_2["node_vVYx-2"]
  n_TjsLkfRK9ERH6KQQvVYx_21["report_bundle"]
  n_TjsLkfRK9ERH6KQQvVYx_23["i_page"]
  n_TjsLkfRK9ERH6KQQvVYx_24["i_time_data"]
  n_TjsLkfRK9ERH6KQQvVYx_27["i_sr04_data"]
  n_TjsLkfRK9ERH6KQQvVYx_28["i_dht_temp"]
  n_TjsLkfRK9ERH6KQQvVYx_3["node_vVYx-3"]
  n_TjsLkfRK9ERH6KQQvVYx_31["i_dht_humi"]
  n_TjsLkfRK9ERH6KQQvVYx_33["i_dnt_valid"]
  n_TjsLkfRK9ERH6KQQvVYx_35["o_frame_data"]
  n_TjsLkfRK9ERH6KQQvVYx_36["o_frame_len"]
  n_TjsLkfRK9ERH6KQQvVYx_4["node_vVYx-4"]
  n_TjsLkfRK9ERH6KQQvVYx_47["start"]
  n_TjsLkfRK9ERH6KQQvVYx_49["i_tx_full"]
  n_TjsLkfRK9ERH6KQQvVYx_5["telemetry_collector"]
  n_TjsLkfRK9ERH6KQQvVYx_51["i_frame_data"]
  n_TjsLkfRK9ERH6KQQvVYx_55["i_frame_len"]
  n_TjsLkfRK9ERH6KQQvVYx_57["push_data"]
  n_TjsLkfRK9ERH6KQQvVYx_59["push"]
  n_TjsLkfRK9ERH6KQQvVYx_6["ascii_frame_formatter"]
  n_TjsLkfRK9ERH6KQQvVYx_61["busy"]
  n_TjsLkfRK9ERH6KQQvVYx_65["pop"]
  n_TjsLkfRK9ERH6KQQvVYx_67["push"]
  n_TjsLkfRK9ERH6KQQvVYx_69["push_data"]
  n_TjsLkfRK9ERH6KQQvVYx_7["ascii_frame_sender"]
  n_TjsLkfRK9ERH6KQQvVYx_73["tx"]
  n_TjsLkfRK9ERH6KQQvVYx_75["tx_busy"]
  n_TjsLkfRK9ERH6KQQvVYx_79["event_log_unit"]
  n_TjsLkfRK9ERH6KQQvVYx_8["uart_tx_fifo"]
  n_TjsLkfRK9ERH6KQQvVYx_85["node_VYx-85"]
  n_TjsLkfRK9ERH6KQQvVYx_86["Remote"]
  n_TjsLkfRK9ERH6KQQvVYx_87["node_VYx-87"]
  n_TjsLkfRK9ERH6KQQvVYx_88["Local"]
  n_TjsLkfRK9ERH6KQQvVYx_89["FND"]
  n_TjsLkfRK9ERH6KQQvVYx_9["log_meta"]
  n_TjsLkfRK9ERH6KQQvVYx_90["SR04(JA)"]
  n_TjsLkfRK9ERH6KQQvVYx_91["LED"]
  n_TjsLkfRK9ERH6KQQvVYx_95["tx"]
  n_gGfTAmhhxMlWeQVoEItu_1["node_EItu-1"]
  n_gGfTAmhhxMlWeQVoEItu_10["fnd_dht11"]
  n_gGfTAmhhxMlWeQVoEItu_12["fnd_com"]
  n_gGfTAmhhxMlWeQVoEItu_14["fnd_data"]
  n_gGfTAmhhxMlWeQVoEItu_2["current_context"]
  n_gGfTAmhhxMlWeQVoEItu_3["display_unit"]
  n_gGfTAmhhxMlWeQVoEItu_6["fnd_watch_stop_watch"]
  n_gGfTAmhhxMlWeQVoEItu_8["fnd_sr04"]
  n_hVDVISroJmmMc8m8Auw1_10["current_context"]
  n_hVDVISroJmmMc8m8Auw1_11["context_action_dispatcher"]
  n_hVDVISroJmmMc8m8Auw1_12["watch_stopwatch_unit"]
  n_hVDVISroJmmMc8m8Auw1_13["sr04_unit"]
  n_hVDVISroJmmMc8m8Auw1_14["dht11_unit"]
  n_hVDVISroJmmMc8m8Auw1_15["event_log_unit"]
  n_hVDVISroJmmMc8m8Auw1_17["ascii_frame_formatter"]
  n_hVDVISroJmmMc8m8Auw1_19["ascii_frame_sender"]
  n_hVDVISroJmmMc8m8Auw1_2["fnd_[watch/stopwatch/sr04/dht11]"]
  n_hVDVISroJmmMc8m8Auw1_21["tx"]
  n_hVDVISroJmmMc8m8Auw1_22["uart_tx_fifo"]
  n_hVDVISroJmmMc8m8Auw1_24["telemetry_collector"]
  n_hVDVISroJmmMc8m8Auw1_25["Remote"]
  n_hVDVISroJmmMc8m8Auw1_26["Local"]
  n_hVDVISroJmmMc8m8Auw1_28["fnd_comfnd_data"]
  n_hVDVISroJmmMc8m8Auw1_29["display_unit"]
  n_hVDVISroJmmMc8m8Auw1_3["function_unit"]
  n_hVDVISroJmmMc8m8Auw1_30["FND"]
  n_hVDVISroJmmMc8m8Auw1_32["[watch/stopwatch/sr04/dht11]_payload"]
  n_hVDVISroJmmMc8m8Auw1_33["SR04(JA)"]
  n_hVDVISroJmmMc8m8Auw1_35["trig"]
  n_hVDVISroJmmMc8m8Auw1_36["LED"]
  n_hVDVISroJmmMc8m8Auw1_38["led[2:0]"]
  n_hVDVISroJmmMc8m8Auw1_5["control_pulsesrefresh_reqsnap_req"]
  n_hVDVISroJmmMc8m8Auw1_6["control_unit"]
  n_hVDVISroJmmMc8m8Auw1_8["control_event_arbiter"]
  n_hVDVISroJmmMc8m8Auw1_3 --> n_hVDVISroJmmMc8m8Auw1_29
  n_hVDVISroJmmMc8m8Auw1_6 --> n_hVDVISroJmmMc8m8Auw1_3
  n_hVDVISroJmmMc8m8Auw1_8 --> n_hVDVISroJmmMc8m8Auw1_11
  n_hVDVISroJmmMc8m8Auw1_11 --> n_hVDVISroJmmMc8m8Auw1_29
  n_hVDVISroJmmMc8m8Auw1_17 --> n_hVDVISroJmmMc8m8Auw1_19
  n_hVDVISroJmmMc8m8Auw1_19 --> n_hVDVISroJmmMc8m8Auw1_22
  n_hVDVISroJmmMc8m8Auw1_22 --> n_hVDVISroJmmMc8m8Auw1_25
  n_hVDVISroJmmMc8m8Auw1_24 --> n_hVDVISroJmmMc8m8Auw1_17
  n_hVDVISroJmmMc8m8Auw1_29 --> n_hVDVISroJmmMc8m8Auw1_30
  n_hVDVISroJmmMc8m8Auw1_3 --> n_hVDVISroJmmMc8m8Auw1_24
  n_hVDVISroJmmMc8m8Auw1_13 --> n_hVDVISroJmmMc8m8Auw1_33
  n_hVDVISroJmmMc8m8Auw1_14 --> n_hVDVISroJmmMc8m8Auw1_36
  n_hVDVISroJmmMc8m8Auw1_11 --> n_hVDVISroJmmMc8m8Auw1_24
