flowchart LR
  n_l8_BoaSIQ5hj2dUQ6oXH_11["ram_vif"]
  n_l8_BoaSIQ5hj2dUQ6oXH_13["monitor"]
  n_l8_BoaSIQ5hj2dUQ6oXH_14["transaction"]
  n_l8_BoaSIQ5hj2dUQ6oXH_15["scoreboard"]
  n_l8_BoaSIQ5hj2dUQ6oXH_16["transaction"]
  n_l8_BoaSIQ5hj2dUQ6oXH_18["mailbox"]
  n_l8_BoaSIQ5hj2dUQ6oXH_2["ram"]
  n_l8_BoaSIQ5hj2dUQ6oXH_21["we"]
  n_l8_BoaSIQ5hj2dUQ6oXH_23["addr,wdata"]
  n_l8_BoaSIQ5hj2dUQ6oXH_24["8"]
  n_l8_BoaSIQ5hj2dUQ6oXH_26["clk"]
  n_l8_BoaSIQ5hj2dUQ6oXH_28["clk we"]
  n_l8_BoaSIQ5hj2dUQ6oXH_29["rdata,addr"]
  n_l8_BoaSIQ5hj2dUQ6oXH_3["generator"]
  n_l8_BoaSIQ5hj2dUQ6oXH_30["8"]
  n_l8_BoaSIQ5hj2dUQ6oXH_32["event_gen_next"]
  n_l8_BoaSIQ5hj2dUQ6oXH_5["transaction"]
  n_l8_BoaSIQ5hj2dUQ6oXH_7["mailbox"]
  n_l8_BoaSIQ5hj2dUQ6oXH_8["driver"]
  n_l8_BoaSIQ5hj2dUQ6oXH_9["ram_vif"]
  n_l8_BoaSIQ5hj2dUQ6oXH_3 --> n_l8_BoaSIQ5hj2dUQ6oXH_7
  n_l8_BoaSIQ5hj2dUQ6oXH_7 --> n_l8_BoaSIQ5hj2dUQ6oXH_8
  n_l8_BoaSIQ5hj2dUQ6oXH_13 --> n_l8_BoaSIQ5hj2dUQ6oXH_18
  n_l8_BoaSIQ5hj2dUQ6oXH_15 --> n_l8_BoaSIQ5hj2dUQ6oXH_3
  n_l8_BoaSIQ5hj2dUQ6oXH_18 --> n_l8_BoaSIQ5hj2dUQ6oXH_15
