flowchart LR
  n_JND3kyrR1L1Zv8udtbI__4["Data<br/>Memory (RAM)"]
  n_zjug9o3QdesyKxwelZWT_5["Instruction Memory<br/>(ROM)"]
  n_zjug9o3QdesyKxwelZWT_6["Instruction Field Split"]
  n_zjug9o3QdesyKxwelZWT_7["Control Unit"]
  n_zjug9o3QdesyKxwelZWT_8["register file"]
  n_zjug9o3QdesyKxwelZWT_9["ALU"]
