flowchart LR
  n_6diTfT2f9CHFYMh8c663_122["rst"]
  n_6diTfT2f9CHFYMh8c663_124["clk"]
  n_6diTfT2f9CHFYMh8c663_125["push"]
  n_6diTfT2f9CHFYMh8c663_127["pop"]
  n_6diTfT2f9CHFYMh8c663_133["full"]
  n_6diTfT2f9CHFYMh8c663_135["empty"]
  n_6diTfT2f9CHFYMh8c663_138["wptr"]
  n_6diTfT2f9CHFYMh8c663_141["rptr"]
  n_6diTfT2f9CHFYMh8c663_142["wdata[7:0]"]
  n_6diTfT2f9CHFYMh8c663_144["we"]
  n_6diTfT2f9CHFYMh8c663_147["waddr"]
  n_6diTfT2f9CHFYMh8c663_149["clk"]
  n_6diTfT2f9CHFYMh8c663_151["raddr"]
  n_6diTfT2f9CHFYMh8c663_153["rdata[7:0]"]
  n_6diTfT2f9CHFYMh8c663_157["baut_tick"]
  n_6diTfT2f9CHFYMh8c663_16["uart_fifo_loopback"]
  n_6diTfT2f9CHFYMh8c663_163["clk"]
  n_6diTfT2f9CHFYMh8c663_166["rst"]
  n_6diTfT2f9CHFYMh8c663_168["tx_data[7:0]"]
  n_6diTfT2f9CHFYMh8c663_17["UART_RX"]
  n_6diTfT2f9CHFYMh8c663_171["tx_start"]
  n_6diTfT2f9CHFYMh8c663_18["FIFO"]
  n_6diTfT2f9CHFYMh8c663_20["FIFO"]
  n_6diTfT2f9CHFYMh8c663_23["register_file"]
  n_6diTfT2f9CHFYMh8c663_24["control_unit"]
  n_6diTfT2f9CHFYMh8c663_28["rx"]
  n_6diTfT2f9CHFYMh8c663_29["rst"]
  n_6diTfT2f9CHFYMh8c663_30["clk"]
  n_6diTfT2f9CHFYMh8c663_31["baut_tick"]
  n_6diTfT2f9CHFYMh8c663_43["rst"]
  n_6diTfT2f9CHFYMh8c663_45["clk"]
  n_6diTfT2f9CHFYMh8c663_56["rx_done"]
  n_6diTfT2f9CHFYMh8c663_57["rx_data[7:0]"]
  n_6diTfT2f9CHFYMh8c663_59["push_data[7:0]"]
  n_6diTfT2f9CHFYMh8c663_63["push"]
  n_6diTfT2f9CHFYMh8c663_66["pop"]
  n_6diTfT2f9CHFYMh8c663_68["pop_data[7:0]"]
  n_6diTfT2f9CHFYMh8c663_70["empty"]
  n_6diTfT2f9CHFYMh8c663_72["full"]
  n_6diTfT2f9CHFYMh8c663_77["UART_TX"]
  n_6diTfT2f9CHFYMh8c663_82["baud_tick_gen"]
  n_6diTfT2f9CHFYMh8c663_88["rst"]
  n_6diTfT2f9CHFYMh8c663_90["clk"]
  n_6diTfT2f9CHFYMh8c663_91["o_baud_tick"]
  n_6diTfT2f9CHFYMh8c663_96["rst"]
  n_6diTfT2f9CHFYMh8c663_98["clk"]
  n_FnVJ_ZV7FgGopvtu0Sig_0["tx"]
  n_GvoThWHFuS_1IchO3jJF_140["gen2scb_mbox"]
  n_GvoThWHFuS_1IchO3jJF_148["event_mon_next"]
  n_GvoThWHFuS_1IchO3jJF_29["fifo_environment"]
  n_GvoThWHFuS_1IchO3jJF_31["fifo_generator"]
  n_GvoThWHFuS_1IchO3jJF_32["fifo_item"]
  n_GvoThWHFuS_1IchO3jJF_34["gen2drv<br/>_mbox"]
  n_GvoThWHFuS_1IchO3jJF_35["fifo_driver"]
  n_GvoThWHFuS_1IchO3jJF_37["fifo_item"]
  n_GvoThWHFuS_1IchO3jJF_39["fifo_if"]
  n_GvoThWHFuS_1IchO3jJF_40["virtual<br/>fifo_if"]
  n_GvoThWHFuS_1IchO3jJF_41["dut"]
  n_GvoThWHFuS_1IchO3jJF_43["fifo_scoreboard"]
  n_GvoThWHFuS_1IchO3jJF_44["fifo_item"]
  n_GvoThWHFuS_1IchO3jJF_45["fifo_monitor"]
  n_GvoThWHFuS_1IchO3jJF_46["fifo_item"]
  n_GvoThWHFuS_1IchO3jJF_48["virtual<br/>fifo_if"]
  n_GvoThWHFuS_1IchO3jJF_52["mon2scb<br/>_mbox"]
  n_LZPBkAAFYlaMrTieN31G_1["tx_environment"]
  n_LZPBkAAFYlaMrTieN31G_10["tx_item"]
  n_LZPBkAAFYlaMrTieN31G_12["tx_if"]
  n_LZPBkAAFYlaMrTieN31G_13["virtual<br/>tx_if"]
  n_LZPBkAAFYlaMrTieN31G_14["dut"]
  n_LZPBkAAFYlaMrTieN31G_16["event_gen_next"]
  n_LZPBkAAFYlaMrTieN31G_17["tx_scoreboard"]
  n_LZPBkAAFYlaMrTieN31G_18["tx_item"]
  n_LZPBkAAFYlaMrTieN31G_19["tx_monitor"]
  n_LZPBkAAFYlaMrTieN31G_20["tx_item"]
  n_LZPBkAAFYlaMrTieN31G_22["virtual<br/>tx_if"]
  n_LZPBkAAFYlaMrTieN31G_26["mon2scb<br/>_mbox"]
  n_LZPBkAAFYlaMrTieN31G_29["gen2scb_mbox"]
  n_LZPBkAAFYlaMrTieN31G_4["tx_generator"]
  n_LZPBkAAFYlaMrTieN31G_5["tx_item"]
  n_LZPBkAAFYlaMrTieN31G_7["gen2drv<br/>_mbox"]
  n_LZPBkAAFYlaMrTieN31G_8["tx_driver"]
  n_RMz_HrEWjncAzhdxbK6D_1["dut"]
  n_RMz_HrEWjncAzhdxbK6D_10["driver"]
  n_RMz_HrEWjncAzhdxbK6D_12["item"]
  n_RMz_HrEWjncAzhdxbK6D_17["interface instance"]
  n_RMz_HrEWjncAzhdxbK6D_34["virtual_<br/>interface"]
  n_RMz_HrEWjncAzhdxbK6D_37["dut"]
  n_RMz_HrEWjncAzhdxbK6D_4["environment"]
  n_RMz_HrEWjncAzhdxbK6D_5["generator"]
  n_RMz_HrEWjncAzhdxbK6D_7["item"]
  n_RMz_HrEWjncAzhdxbK6D_9["mailbox gen2drv"]
  n_WJbyiAHSDaECVwYxXuOC_1["top_environment"]
  n_WJbyiAHSDaECVwYxXuOC_10["top_item"]
  n_WJbyiAHSDaECVwYxXuOC_12["top_if"]
  n_WJbyiAHSDaECVwYxXuOC_13["virtual<br/>top_if"]
  n_WJbyiAHSDaECVwYxXuOC_14["dut"]
  n_WJbyiAHSDaECVwYxXuOC_16["event_gen_next"]
  n_WJbyiAHSDaECVwYxXuOC_17["top_scoreboard"]
  n_WJbyiAHSDaECVwYxXuOC_18["top_item"]
  n_WJbyiAHSDaECVwYxXuOC_19["top_monitor"]
  n_WJbyiAHSDaECVwYxXuOC_20["top_item"]
  n_WJbyiAHSDaECVwYxXuOC_22["virtual<br/>top_if"]
  n_WJbyiAHSDaECVwYxXuOC_26["mon2scb<br/>_mbox"]
  n_WJbyiAHSDaECVwYxXuOC_29["gen2scb_mbox"]
  n_WJbyiAHSDaECVwYxXuOC_32["gen2mon<br/>_mbox"]
  n_WJbyiAHSDaECVwYxXuOC_4["top_generator"]
  n_WJbyiAHSDaECVwYxXuOC_5["top_item"]
  n_WJbyiAHSDaECVwYxXuOC_7["gen2drv<br/>_mbox"]
  n_WJbyiAHSDaECVwYxXuOC_8["top_driver"]
  n_Wg0f5VRh3PGvLouv_y46_0["bit timing"]
  n_Wg0f5VRh3PGvLouv_y46_2["byte receive"]
  n_Wg0f5VRh3PGvLouv_y46_3["data buffer"]
  n_Wg0f5VRh3PGvLouv_y46_4["byte transmit"]
  n_Wg0f5VRh3PGvLouv_y46_5["pointer control"]
  n_Wg0f5VRh3PGvLouv_y46_6["data storage"]
  n_ZGkF4VGaBri_aRoA1dya_0["uart_fifo_loopback"]
  n_ZGkF4VGaBri_aRoA1dya_1["FIFO"]
  n_ZGkF4VGaBri_aRoA1dya_2["UART_RX"]
  n_ZGkF4VGaBri_aRoA1dya_4["baud_tick_gen"]
  n_ZGkF4VGaBri_aRoA1dya_5["Remote"]
  n_ZGkF4VGaBri_aRoA1dya_6["Remote"]
  n_ZGkF4VGaBri_aRoA1dya_7["UART_TX"]
  n_ePT9l0OBU5ckNXm0DFw9_1["env"]
  n_ePT9l0OBU5ckNXm0DFw9_13["interface instance"]
  n_ePT9l0OBU5ckNXm0DFw9_15["monitor"]
  n_ePT9l0OBU5ckNXm0DFw9_16["item"]
  n_ePT9l0OBU5ckNXm0DFw9_18["event_gen_next"]
  n_ePT9l0OBU5ckNXm0DFw9_19["scoreboard"]
  n_ePT9l0OBU5ckNXm0DFw9_2["case_generator"]
  n_ePT9l0OBU5ckNXm0DFw9_20["item"]
  n_ePT9l0OBU5ckNXm0DFw9_22["mailbox mon2scb"]
  n_ePT9l0OBU5ckNXm0DFw9_30["virtual_interface"]
  n_ePT9l0OBU5ckNXm0DFw9_32["virtual_interface"]
  n_ePT9l0OBU5ckNXm0DFw9_4["item"]
  n_ePT9l0OBU5ckNXm0DFw9_6["mailbox gen2drv"]
  n_ePT9l0OBU5ckNXm0DFw9_7["driver"]
  n_ePT9l0OBU5ckNXm0DFw9_9["item"]
  n_vh1eEx2FdvI0h0XfNtzR_1["scoreboard"]
  n_vh1eEx2FdvI0h0XfNtzR_18["monitor"]
  n_vh1eEx2FdvI0h0XfNtzR_19["item"]
  n_vh1eEx2FdvI0h0XfNtzR_2["item"]
  n_vh1eEx2FdvI0h0XfNtzR_20["virtual_<br/>interface"]
  n_vh1eEx2FdvI0h0XfNtzR_3["mailbox mon2scb"]
  n_vh1eEx2FdvI0h0XfNtzR_56["event_gen_next"]
  n_wqIhplem1QiN_lLYHW1f_1["rx_environment"]
  n_wqIhplem1QiN_lLYHW1f_10["rx_driver"]
  n_wqIhplem1QiN_lLYHW1f_12["rx_item"]
  n_wqIhplem1QiN_lLYHW1f_14["rx_if"]
  n_wqIhplem1QiN_lLYHW1f_15["virtual<br/>rx_if"]
  n_wqIhplem1QiN_lLYHW1f_16["dut"]
  n_wqIhplem1QiN_lLYHW1f_17["rx_scoreboard"]
  n_wqIhplem1QiN_lLYHW1f_18["rx_item"]
  n_wqIhplem1QiN_lLYHW1f_19["rx_monitor"]
  n_wqIhplem1QiN_lLYHW1f_20["rx_item"]
  n_wqIhplem1QiN_lLYHW1f_22["virtual<br/>rx_if"]
  n_wqIhplem1QiN_lLYHW1f_26["mon2scb<br/>_mbox"]
  n_wqIhplem1QiN_lLYHW1f_29["gen2scb_mbox"]
  n_wqIhplem1QiN_lLYHW1f_4["rx_generator"]
  n_wqIhplem1QiN_lLYHW1f_5["rx_item"]
  n_wqIhplem1QiN_lLYHW1f_7["gen2drv<br/>_mbox"]
  n_ZGkF4VGaBri_aRoA1dya_0 --> n_ZGkF4VGaBri_aRoA1dya_6
  n_ZGkF4VGaBri_aRoA1dya_2 --> n_ZGkF4VGaBri_aRoA1dya_1
  n_ZGkF4VGaBri_aRoA1dya_0 --> n_ZGkF4VGaBri_aRoA1dya_2
  n_ZGkF4VGaBri_aRoA1dya_5 --> n_ZGkF4VGaBri_aRoA1dya_0
  n_6diTfT2f9CHFYMh8c663_91 --> n_6diTfT2f9CHFYMh8c663_31
  n_6diTfT2f9CHFYMh8c663_91 --> n_6diTfT2f9CHFYMh8c663_157
  n_6diTfT2f9CHFYMh8c663_20 --> n_6diTfT2f9CHFYMh8c663_18
  n_6diTfT2f9CHFYMh8c663_20 --> n_6diTfT2f9CHFYMh8c663_18
  n_ZGkF4VGaBri_aRoA1dya_0 --> n_6diTfT2f9CHFYMh8c663_16
  n_ePT9l0OBU5ckNXm0DFw9_2 --> n_ePT9l0OBU5ckNXm0DFw9_6
  n_ePT9l0OBU5ckNXm0DFw9_6 --> n_ePT9l0OBU5ckNXm0DFw9_7
  n_ePT9l0OBU5ckNXm0DFw9_9 --> n_ePT9l0OBU5ckNXm0DFw9_30
  n_ePT9l0OBU5ckNXm0DFw9_13 --> n_RMz_HrEWjncAzhdxbK6D_1
  n_ePT9l0OBU5ckNXm0DFw9_15 --> n_ePT9l0OBU5ckNXm0DFw9_22
  n_ePT9l0OBU5ckNXm0DFw9_19 --> n_ePT9l0OBU5ckNXm0DFw9_2
  n_ePT9l0OBU5ckNXm0DFw9_22 --> n_ePT9l0OBU5ckNXm0DFw9_19
  n_ePT9l0OBU5ckNXm0DFw9_32 --> n_ePT9l0OBU5ckNXm0DFw9_16
  n_RMz_HrEWjncAzhdxbK6D_5 --> n_RMz_HrEWjncAzhdxbK6D_9
  n_RMz_HrEWjncAzhdxbK6D_9 --> n_RMz_HrEWjncAzhdxbK6D_10
  n_RMz_HrEWjncAzhdxbK6D_17 --> n_RMz_HrEWjncAzhdxbK6D_37
  n_vh1eEx2FdvI0h0XfNtzR_1 --> n_RMz_HrEWjncAzhdxbK6D_5
  n_vh1eEx2FdvI0h0XfNtzR_3 --> n_vh1eEx2FdvI0h0XfNtzR_1
  n_GvoThWHFuS_1IchO3jJF_31 --> n_GvoThWHFuS_1IchO3jJF_34
  n_GvoThWHFuS_1IchO3jJF_31 --> n_GvoThWHFuS_1IchO3jJF_140
  n_GvoThWHFuS_1IchO3jJF_34 --> n_GvoThWHFuS_1IchO3jJF_35
  n_GvoThWHFuS_1IchO3jJF_35 --> n_GvoThWHFuS_1IchO3jJF_45
  n_GvoThWHFuS_1IchO3jJF_39 --> n_GvoThWHFuS_1IchO3jJF_41
  n_GvoThWHFuS_1IchO3jJF_140 --> n_GvoThWHFuS_1IchO3jJF_43
  n_LZPBkAAFYlaMrTieN31G_4 --> n_LZPBkAAFYlaMrTieN31G_7
  n_LZPBkAAFYlaMrTieN31G_4 --> n_LZPBkAAFYlaMrTieN31G_29
  n_LZPBkAAFYlaMrTieN31G_7 --> n_LZPBkAAFYlaMrTieN31G_8
  n_LZPBkAAFYlaMrTieN31G_12 --> n_LZPBkAAFYlaMrTieN31G_14
  n_LZPBkAAFYlaMrTieN31G_17 --> n_LZPBkAAFYlaMrTieN31G_4
  n_LZPBkAAFYlaMrTieN31G_29 --> n_LZPBkAAFYlaMrTieN31G_17
  n_wqIhplem1QiN_lLYHW1f_4 --> n_wqIhplem1QiN_lLYHW1f_7
  n_wqIhplem1QiN_lLYHW1f_4 --> n_wqIhplem1QiN_lLYHW1f_29
  n_wqIhplem1QiN_lLYHW1f_7 --> n_wqIhplem1QiN_lLYHW1f_10
  n_wqIhplem1QiN_lLYHW1f_14 --> n_wqIhplem1QiN_lLYHW1f_16
  n_wqIhplem1QiN_lLYHW1f_29 --> n_wqIhplem1QiN_lLYHW1f_17
  n_WJbyiAHSDaECVwYxXuOC_4 --> n_WJbyiAHSDaECVwYxXuOC_7
  n_WJbyiAHSDaECVwYxXuOC_4 --> n_WJbyiAHSDaECVwYxXuOC_29
  n_WJbyiAHSDaECVwYxXuOC_4 --> n_WJbyiAHSDaECVwYxXuOC_32
  n_WJbyiAHSDaECVwYxXuOC_7 --> n_WJbyiAHSDaECVwYxXuOC_8
  n_WJbyiAHSDaECVwYxXuOC_12 --> n_WJbyiAHSDaECVwYxXuOC_14
  n_WJbyiAHSDaECVwYxXuOC_17 --> n_WJbyiAHSDaECVwYxXuOC_4
  n_WJbyiAHSDaECVwYxXuOC_29 --> n_WJbyiAHSDaECVwYxXuOC_17
  n_WJbyiAHSDaECVwYxXuOC_32 --> n_WJbyiAHSDaECVwYxXuOC_19
