flowchart LR
  n_pyArTMUBqx2ekubFKROX_1["node_KROX-1"]
  n_pyArTMUBqx2ekubFKROX_12["tick_cnt >= 11"]
  n_pyArTMUBqx2ekubFKROX_2["echo ==0"]
  n_pyArTMUBqx2ekubFKROX_23["node_ROX-23"]
  n_pyArTMUBqx2ekubFKROX_3["Respose"]
  n_pyArTMUBqx2ekubFKROX_33["trig =0"]
  n_pyArTMUBqx2ekubFKROX_34["trig =0"]
  n_pyArTMUBqx2ekubFKROX_4["node_KROX-4"]
  n_pyArTMUBqx2ekubFKROX_40["Ｆ"]
  n_pyArTMUBqx2ekubFKROX_41["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_42["node_ROX-42"]
  n_pyArTMUBqx2ekubFKROX_43["tick_us == 1"]
  n_pyArTMUBqx2ekubFKROX_44["tick_cnt +1"]
  n_pyArTMUBqx2ekubFKROX_48["node_ROX-48"]
  n_pyArTMUBqx2ekubFKROX_49["tick_us == 1"]
  n_pyArTMUBqx2ekubFKROX_5["tick_cnt ++"]
  n_pyArTMUBqx2ekubFKROX_53["tick_cnt = 0"]
  n_pyArTMUBqx2ekubFKROX_56["tick_us == 1"]
  n_pyArTMUBqx2ekubFKROX_60["node_ROX-60"]
  n_pyArTMUBqx2ekubFKROX_61["tick_cnt /58"]
  n_pyArTMUBqx2ekubFKROX_65["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_66["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_67["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_68["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_69["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_70["Ｔ"]
  n_pyArTMUBqx2ekubFKROX_72["F"]
  n_pyArTMUBqx2ekubFKROX_74["F"]
  n_pyArTMUBqx2ekubFKROX_76["F"]
  n_pyArTMUBqx2ekubFKROX_78["F"]
  n_pyArTMUBqx2ekubFKROX_80["F"]
  n_pyArTMUBqx2ekubFKROX_82["F"]
  n_pyArTMUBqx2ekubFKROX_83["<distance>"]
  n_qU6jsDxPJs_IhxhBXcGn_1["node_XcGn-1"]
  n_qU6jsDxPJs_IhxhBXcGn_10["WAIT"]
  n_qU6jsDxPJs_IhxhBXcGn_11["node_cGn-11"]
  n_qU6jsDxPJs_IhxhBXcGn_13["node_cGn-13"]
  n_qU6jsDxPJs_IhxhBXcGn_14["trig = 1"]
  n_qU6jsDxPJs_IhxhBXcGn_17["node_cGn-17"]
  n_qU6jsDxPJs_IhxhBXcGn_18["echo ==1"]
  n_qU6jsDxPJs_IhxhBXcGn_2["IDLE"]
  n_qU6jsDxPJs_IhxhBXcGn_3["node_XcGn-3"]
  n_qU6jsDxPJs_IhxhBXcGn_4["START"]
  n_qU6jsDxPJs_IhxhBXcGn_5["node_XcGn-5"]
  n_qU6jsDxPJs_IhxhBXcGn_6["sr04_start == 1"]
  n_qU6jsDxPJs_IhxhBXcGn_9["node_XcGn-9"]
  n_qU6jsDxPJs_IhxhBXcGn_5 --> n_qU6jsDxPJs_IhxhBXcGn_3
  n_qU6jsDxPJs_IhxhBXcGn_9 --> n_pyArTMUBqx2ekubFKROX_33
  n_qU6jsDxPJs_IhxhBXcGn_13 --> n_qU6jsDxPJs_IhxhBXcGn_9
  n_qU6jsDxPJs_IhxhBXcGn_17 --> n_pyArTMUBqx2ekubFKROX_53
  n_pyArTMUBqx2ekubFKROX_1 --> n_pyArTMUBqx2ekubFKROX_60
  n_pyArTMUBqx2ekubFKROX_53 --> n_qU6jsDxPJs_IhxhBXcGn_11
  n_pyArTMUBqx2ekubFKROX_60 --> n_qU6jsDxPJs_IhxhBXcGn_1
