flowchart LR
  n_wHDCfNWy0C5bdR1iGWTU_1["Manager"]
  n_wHDCfNWy0C5bdR1iGWTU_10["node_WTU-10"]
  n_wHDCfNWy0C5bdR1iGWTU_11["RAM"]
  n_wHDCfNWy0C5bdR1iGWTU_111["Control Unit"]
  n_wHDCfNWy0C5bdR1iGWTU_113["Instruction Memory(ROM)"]
  n_wHDCfNWy0C5bdR1iGWTU_116["RV32I"]
  n_wHDCfNWy0C5bdR1iGWTU_117["DataPath"]
  n_wHDCfNWy0C5bdR1iGWTU_119["Control<br/>Unit"]
  n_wHDCfNWy0C5bdR1iGWTU_12["node_WTU-12"]
  n_wHDCfNWy0C5bdR1iGWTU_121["Master(APB Requester)"]
  n_wHDCfNWy0C5bdR1iGWTU_122["DataPath"]
  n_wHDCfNWy0C5bdR1iGWTU_124["Address<br/>Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_125["Control Unit"]
  n_wHDCfNWy0C5bdR1iGWTU_128["Slave(APB Completer)"]
  n_wHDCfNWy0C5bdR1iGWTU_129["RAM"]
  n_wHDCfNWy0C5bdR1iGWTU_13["GPO"]
  n_wHDCfNWy0C5bdR1iGWTU_130["GPIO"]
  n_wHDCfNWy0C5bdR1iGWTU_131["GPI"]
  n_wHDCfNWy0C5bdR1iGWTU_132["GPO"]
  n_wHDCfNWy0C5bdR1iGWTU_133["FND"]
  n_wHDCfNWy0C5bdR1iGWTU_135["instr_code[31:0]"]
  n_wHDCfNWy0C5bdR1iGWTU_137["instr_addr[31:0]"]
  n_wHDCfNWy0C5bdR1iGWTU_14["GPI"]
  n_wHDCfNWy0C5bdR1iGWTU_15["GPIO"]
  n_wHDCfNWy0C5bdR1iGWTU_16["0000_0000"]
  n_wHDCfNWy0C5bdR1iGWTU_17["0000_FFFF"]
  n_wHDCfNWy0C5bdR1iGWTU_18["1000_0000"]
  n_wHDCfNWy0C5bdR1iGWTU_19["1000_FFFF"]
  n_wHDCfNWy0C5bdR1iGWTU_2["ADDR Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_20["2000_0000"]
  n_wHDCfNWy0C5bdR1iGWTU_21["2000_1000"]
  n_wHDCfNWy0C5bdR1iGWTU_22["2000_2000"]
  n_wHDCfNWy0C5bdR1iGWTU_23["2000_3000"]
  n_wHDCfNWy0C5bdR1iGWTU_26["APB Control Unit"]
  n_wHDCfNWy0C5bdR1iGWTU_3["node_GWTU-3"]
  n_wHDCfNWy0C5bdR1iGWTU_30["Instruction Memory<br/>(ROM)"]
  n_wHDCfNWy0C5bdR1iGWTU_31["RV32I<br/>(CPU)"]
  n_wHDCfNWy0C5bdR1iGWTU_35["Instruction Memory(ROM)"]
  n_wHDCfNWy0C5bdR1iGWTU_38["RV32I"]
  n_wHDCfNWy0C5bdR1iGWTU_39["DataPath"]
  n_wHDCfNWy0C5bdR1iGWTU_4["ROM"]
  n_wHDCfNWy0C5bdR1iGWTU_41["Control<br/>Unit"]
  n_wHDCfNWy0C5bdR1iGWTU_5["node_GWTU-5"]
  n_wHDCfNWy0C5bdR1iGWTU_51["Master<br/>(APB Reuqester)"]
  n_wHDCfNWy0C5bdR1iGWTU_52["Slave<br/>(APB Completer)"]
  n_wHDCfNWy0C5bdR1iGWTU_55["Master(APB Requester)"]
  n_wHDCfNWy0C5bdR1iGWTU_56["DataPath"]
  n_wHDCfNWy0C5bdR1iGWTU_58["Address<br/>Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_6["ADDR Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_64["Slave(APB Completer)"]
  n_wHDCfNWy0C5bdR1iGWTU_67["RAM"]
  n_wHDCfNWy0C5bdR1iGWTU_68["GPIO"]
  n_wHDCfNWy0C5bdR1iGWTU_69["GPI"]
  n_wHDCfNWy0C5bdR1iGWTU_7["ADDR Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_70["GPO"]
  n_wHDCfNWy0C5bdR1iGWTU_71["FND"]
  n_wHDCfNWy0C5bdR1iGWTU_8["ADDR Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_9["ADDR Decoder"]
  n_wHDCfNWy0C5bdR1iGWTU_41 --> n_wHDCfNWy0C5bdR1iGWTU_39
  n_wHDCfNWy0C5bdR1iGWTU_58 --> n_wHDCfNWy0C5bdR1iGWTU_56
  n_wHDCfNWy0C5bdR1iGWTU_119 --> n_wHDCfNWy0C5bdR1iGWTU_117
  n_wHDCfNWy0C5bdR1iGWTU_124 --> n_wHDCfNWy0C5bdR1iGWTU_122
