flowchart LR
  n_NSqoYb7kwDBbw9KJm_ng_1["node_m_ng-1"]
  n_NSqoYb7kwDBbw9KJm_ng_2["node_m_ng-2"]
  n_XCGefnzt3Sx8slRFdQB6_1["Stopwatch, Watch Module"]
  n_XCGefnzt3Sx8slRFdQB6_22["FND"]
  n_XCGefnzt3Sx8slRFdQB6_26["sw[1:0]"]
  n_XCGefnzt3Sx8slRFdQB6_4["SR04_Controller"]
  n_XCGefnzt3Sx8slRFdQB6_5["DHT11_HUMID_TEMP"]
  n_XCGefnzt3Sx8slRFdQB6_7["node_dQB6-7"]
  n_sgKVDU6i_RNd5s9dl7Hf_1["node_l7Hf-1"]
  n_yRs9L5DDgcKWez_suBbv_109["ASCII_Decoder"]
  n_yRs9L5DDgcKWez_suBbv_11["baud_tick_gen"]
  n_yRs9L5DDgcKWez_suBbv_115["8"]
  n_yRs9L5DDgcKWez_suBbv_116["8"]
  n_yRs9L5DDgcKWez_suBbv_12["node_Bbv-12"]
  n_yRs9L5DDgcKWez_suBbv_124["r || R"]
  n_yRs9L5DDgcKWez_suBbv_127["l || L"]
  n_yRs9L5DDgcKWez_suBbv_128["u || U"]
  n_yRs9L5DDgcKWez_suBbv_129["d || D"]
  n_yRs9L5DDgcKWez_suBbv_13["rst"]
  n_yRs9L5DDgcKWez_suBbv_130["m || M"]
  n_yRs9L5DDgcKWez_suBbv_133["Control_unit"]
  n_yRs9L5DDgcKWez_suBbv_139["s || S"]
  n_yRs9L5DDgcKWez_suBbv_140["FPGA_Btn"]
  n_yRs9L5DDgcKWez_suBbv_141["Btn_R"]
  n_yRs9L5DDgcKWez_suBbv_142["Btn_L"]
  n_yRs9L5DDgcKWez_suBbv_143["Btn_U"]
  n_yRs9L5DDgcKWez_suBbv_144["Btn_D"]
  n_yRs9L5DDgcKWez_suBbv_148["node_bv-148"]
  n_yRs9L5DDgcKWez_suBbv_149["8"]
  n_yRs9L5DDgcKWez_suBbv_150["node_bv-150"]
  n_yRs9L5DDgcKWez_suBbv_151["rst"]
  n_yRs9L5DDgcKWez_suBbv_152["8"]
  n_yRs9L5DDgcKWez_suBbv_153["Rx- done"]
  n_yRs9L5DDgcKWez_suBbv_154["pop_data"]
  n_yRs9L5DDgcKWez_suBbv_155["pop"]
  n_yRs9L5DDgcKWez_suBbv_156["empty"]
  n_yRs9L5DDgcKWez_suBbv_157["push_data"]
  n_yRs9L5DDgcKWez_suBbv_158["push"]
  n_yRs9L5DDgcKWez_suBbv_159["full"]
  n_yRs9L5DDgcKWez_suBbv_16["UART_Tx"]
  n_yRs9L5DDgcKWez_suBbv_17["tx_data"]
  n_yRs9L5DDgcKWez_suBbv_19["tx_start"]
  n_yRs9L5DDgcKWez_suBbv_2["PC"]
  n_yRs9L5DDgcKWez_suBbv_21["tx_busy"]
  n_yRs9L5DDgcKWez_suBbv_3["Tx"]
  n_yRs9L5DDgcKWez_suBbv_36["Rx"]
  n_yRs9L5DDgcKWez_suBbv_4["Rx"]
  n_yRs9L5DDgcKWez_suBbv_5["UART Rx"]
  n_yRs9L5DDgcKWez_suBbv_51["node_Bbv-51"]
  n_yRs9L5DDgcKWez_suBbv_56["baud_tick"]
  n_yRs9L5DDgcKWez_suBbv_58["baud_tick"]
  n_yRs9L5DDgcKWez_suBbv_7["Rx data"]
  n_yRs9L5DDgcKWez_suBbv_72["FIFO Tx"]
  n_yRs9L5DDgcKWez_suBbv_8["Rx- done"]
  n_yRs9L5DDgcKWez_suBbv_84["FIFO Rx"]
  n_yRs9L5DDgcKWez_suBbv_86["pop_data"]
  n_yRs9L5DDgcKWez_suBbv_88["pop"]
  n_yRs9L5DDgcKWez_suBbv_9["rst"]
  n_yRs9L5DDgcKWez_suBbv_90["empty"]
  n_yRs9L5DDgcKWez_suBbv_91["push_data"]
  n_yRs9L5DDgcKWez_suBbv_93["push"]
  n_yRs9L5DDgcKWez_suBbv_95["full"]
  n_yRs9L5DDgcKWez_suBbv_99["ASCII_sender"]
  n_yRs9L5DDgcKWez_suBbv_11 --> n_yRs9L5DDgcKWez_suBbv_5
  n_yRs9L5DDgcKWez_suBbv_16 --> n_yRs9L5DDgcKWez_suBbv_4
  n_yRs9L5DDgcKWez_suBbv_148 --> n_yRs9L5DDgcKWez_suBbv_16
  n_sgKVDU6i_RNd5s9dl7Hf_1 --> n_yRs9L5DDgcKWez_suBbv_124
  n_yRs9L5DDgcKWez_suBbv_141 --> n_sgKVDU6i_RNd5s9dl7Hf_1
