flowchart LR
  n_1AVZPSrsPg0MGLG_RwkN_1["function_unit"]
  n_1AVZPSrsPg0MGLG_RwkN_10["dht11_unit"]
  n_1AVZPSrsPg0MGLG_RwkN_11["node_wkN-11"]
  n_1AVZPSrsPg0MGLG_RwkN_12["node_wkN-12"]
  n_1AVZPSrsPg0MGLG_RwkN_13["EVENT_SELECTOR"]
  n_1AVZPSrsPg0MGLG_RwkN_14["ACTION_DISPACTER"]
  n_1AVZPSrsPg0MGLG_RwkN_15["local_button_bus"]
  n_1AVZPSrsPg0MGLG_RwkN_16["remote_cmd_bus"]
  n_1AVZPSrsPg0MGLG_RwkN_17["canonical_evt_bus"]
  n_1AVZPSrsPg0MGLG_RwkN_3["control_pulsesrefresh_reqsnap_req"]
  n_1AVZPSrsPg0MGLG_RwkN_4["control_unit"]
  n_1AVZPSrsPg0MGLG_RwkN_6["control_event_arbiter"]
  n_1AVZPSrsPg0MGLG_RwkN_7["context_event_dispatcher"]
  n_1AVZPSrsPg0MGLG_RwkN_8["watch_stopwatch_unit"]
  n_1AVZPSrsPg0MGLG_RwkN_9["sr04_unit"]
  n_ZRII5WbOuysuoFS_0yGD_3["o_stopwatch_msec"]
  n_ZRII5WbOuysuoFS_0yGD_4["i_show_humi"]
  n_ZRII5WbOuysuoFS_0yGD_6["dht11_io"]
  n_bwpoZiZqISLVeRXRRRad_1["canonical_evt_bus"]
  n_bwpoZiZqISLVeRXRRRad_102["o_valid"]
  n_bwpoZiZqISLVeRXRRRad_2["current_context"]
  n_bwpoZiZqISLVeRXRRRad_24["node_Rad-24"]
  n_bwpoZiZqISLVeRXRRRad_25["DECISION_UNIT"]
  n_bwpoZiZqISLVeRXRRRad_26["node_Rad-26"]
  n_bwpoZiZqISLVeRXRRRad_27["EXECUTE_UNIT"]
  n_bwpoZiZqISLVeRXRRRad_28["node_Rad-28"]
  n_bwpoZiZqISLVeRXRRRad_29["node_Rad-29"]
  n_bwpoZiZqISLVeRXRRRad_3["context_change_pulse"]
  n_bwpoZiZqISLVeRXRRRad_30["node_Rad-30"]
  n_bwpoZiZqISLVeRXRRRad_31["stopwatch_unit"]
  n_bwpoZiZqISLVeRXRRRad_32["sr04_unit"]
  n_bwpoZiZqISLVeRXRRRad_34["i_btnD"]
  n_bwpoZiZqISLVeRXRRRad_36["dht11_unit"]
  n_bwpoZiZqISLVeRXRRRad_37["node_Rad-37"]
  n_bwpoZiZqISLVeRXRRRad_38["node_Rad-38"]
  n_bwpoZiZqISLVeRXRRRad_39["node_Rad-39"]
  n_bwpoZiZqISLVeRXRRRad_4["watch_evt_bus"]
  n_bwpoZiZqISLVeRXRRRad_40["node_Rad-40"]
  n_bwpoZiZqISLVeRXRRRad_41["watch_unit"]
  n_bwpoZiZqISLVeRXRRRad_44["i_btnU"]
  n_bwpoZiZqISLVeRXRRRad_46["i_btnL"]
  n_bwpoZiZqISLVeRXRRRad_48["i_sw0"]
  n_bwpoZiZqISLVeRXRRRad_5["stopwatch_evt_bus"]
  n_bwpoZiZqISLVeRXRRRad_50["o_stopwatch_hour"]
  n_bwpoZiZqISLVeRXRRRad_53["o_stopwatch_min"]
  n_bwpoZiZqISLVeRXRRRad_55["o_stopwatch_sec"]
  n_bwpoZiZqISLVeRXRRRad_56["i_display_mode"]
  n_bwpoZiZqISLVeRXRRRad_58["i_btnL/U/D"]
  n_bwpoZiZqISLVeRXRRRad_6["sr04_refresh_req"]
  n_bwpoZiZqISLVeRXRRRad_60["i_btnU_hold"]
  n_bwpoZiZqISLVeRXRRRad_62["i_sw0"]
  n_bwpoZiZqISLVeRXRRRad_64["i_btnD_hold"]
  n_bwpoZiZqISLVeRXRRRad_69["SRC/CMD/EVT"]
  n_bwpoZiZqISLVeRXRRRad_7["dht11_refresh_req"]
  n_bwpoZiZqISLVeRXRRRad_72["o_watch_live_time"]
  n_bwpoZiZqISLVeRXRRRad_74["o_watch_set_index"]
  n_bwpoZiZqISLVeRXRRRad_76["o_watch_set_mode"]
  n_bwpoZiZqISLVeRXRRRad_78["o_watch_set_time"]
  n_bwpoZiZqISLVeRXRRRad_8["ACT"]
  n_bwpoZiZqISLVeRXRRRad_85["i_refresh_req"]
  n_bwpoZiZqISLVeRXRRRad_87["echo"]
  n_bwpoZiZqISLVeRXRRRad_89["trig"]
  n_bwpoZiZqISLVeRXRRRad_9["log_req"]
  n_bwpoZiZqISLVeRXRRRad_91["o_distance_cm"]
  n_bwpoZiZqISLVeRXRRRad_93["i_refresh_req"]
  n_bwpoZiZqISLVeRXRRRad_97["o_humi"]
  n_bwpoZiZqISLVeRXRRRad_99["o_temp"]
  n_1AVZPSrsPg0MGLG_RwkN_4 --> n_1AVZPSrsPg0MGLG_RwkN_1
  n_1AVZPSrsPg0MGLG_RwkN_6 --> n_1AVZPSrsPg0MGLG_RwkN_7
  n_bwpoZiZqISLVeRXRRRad_31 --> n_bwpoZiZqISLVeRXRRRad_31
