flowchart LR
  n_1xamawp9gnZpQtRdpWja_1["out_sel = 1"]
  n_1xamawp9gnZpQtRdpWja_100["tick_cnt + 1"]
  n_1xamawp9gnZpQtRdpWja_108["IDLE"]
  n_1xamawp9gnZpQtRdpWja_110["tick_cnt = 0"]
  n_1xamawp9gnZpQtRdpWja_16["tick_us == 1"]
  n_1xamawp9gnZpQtRdpWja_17["tick_cnt + 1"]
  n_1xamawp9gnZpQtRdpWja_19["tick_cnt > 30"]
  n_1xamawp9gnZpQtRdpWja_32["SYNCL"]
  n_1xamawp9gnZpQtRdpWja_33["SYNCH"]
  n_1xamawp9gnZpQtRdpWja_34["out_sel = 0"]
  n_1xamawp9gnZpQtRdpWja_36["tick_us == 1"]
  n_1xamawp9gnZpQtRdpWja_38["tick_cnt > 40 && dht11_sync2 == 1"]
  n_1xamawp9gnZpQtRdpWja_4["tick_cnt > 19000"]
  n_1xamawp9gnZpQtRdpWja_40["tick_cnt + 1"]
  n_1xamawp9gnZpQtRdpWja_52["DATA_SYNC"]
  n_1xamawp9gnZpQtRdpWja_53["tick_us == 1"]
  n_1xamawp9gnZpQtRdpWja_55["tick_cnt > 40 && dht11_sync2 == ０"]
  n_1xamawp9gnZpQtRdpWja_57["tick_cnt + 1"]
  n_1xamawp9gnZpQtRdpWja_6["dht11 = 1"]
  n_1xamawp9gnZpQtRdpWja_65["tick_us == 1"]
  n_1xamawp9gnZpQtRdpWja_68["dht11_sync2 == 1"]
  n_1xamawp9gnZpQtRdpWja_70["DATA_COUNT"]
  n_1xamawp9gnZpQtRdpWja_75["tick_cnt + 1"]
  n_1xamawp9gnZpQtRdpWja_79["DATA_DECISION"]
  n_1xamawp9gnZpQtRdpWja_80["STOP"]
  n_1xamawp9gnZpQtRdpWja_88["tick_cnt > 50"]
  n_1xamawp9gnZpQtRdpWja_94["tick_us == 1"]
  n_1xamawp9gnZpQtRdpWja_96["tick_cnt > 50"]
  n_3f0HE_8pnrwOXLfxls7N_1["IDLE"]
  n_3f0HE_8pnrwOXLfxls7N_10["tick_cnt + 1"]
  n_3f0HE_8pnrwOXLfxls7N_14["dht11_start == 1"]
  n_3f0HE_8pnrwOXLfxls7N_16["dht11 = 0"]
  n_3f0HE_8pnrwOXLfxls7N_2["START"]
  n_3f0HE_8pnrwOXLfxls7N_3["WAIT"]
  n_3f0HE_8pnrwOXLfxls7N_6["dht11 = 1"]
  n_3f0HE_8pnrwOXLfxls7N_8["tick_us == 1"]
  n_D7PuZc8Kq_5b7wP9eUBl_10["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_11["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_12["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_13["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_14["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_15["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_16["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_17["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_18["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_19["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_20["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_21["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_22["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_23["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_24["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_25["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_26["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_27["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_28["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_29["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_30["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_31["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_32["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_33["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_34["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_35["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_36["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_37["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_4["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_5["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_6["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_7["F"]
  n_D7PuZc8Kq_5b7wP9eUBl_8["T"]
  n_D7PuZc8Kq_5b7wP9eUBl_9["F"]
  n_I3o6vIBZrQdWAhx5R_yA_1["IDLE"]
  n_I3o6vIBZrQdWAhx5R_yA_10["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_106["IDLE"]
  n_I3o6vIBZrQdWAhx5R_yA_108["tick_cnt = 0"]
  n_I3o6vIBZrQdWAhx5R_yA_110["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_112["dht11_sync2 == 0"]
  n_I3o6vIBZrQdWAhx5R_yA_114["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_119["bit = 1 저장<br/>tick_cnt = 0"]
  n_I3o6vIBZrQdWAhx5R_yA_12["dht11_start == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_120["bit_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_121["bit = 0 저장<br/>tick_cnt = 0"]
  n_I3o6vIBZrQdWAhx5R_yA_126["bit_cnt == 39"]
  n_I3o6vIBZrQdWAhx5R_yA_138["T"]
  n_I3o6vIBZrQdWAhx5R_yA_139["F"]
  n_I3o6vIBZrQdWAhx5R_yA_14["dht11 = 0"]
  n_I3o6vIBZrQdWAhx5R_yA_140["T"]
  n_I3o6vIBZrQdWAhx5R_yA_141["F"]
  n_I3o6vIBZrQdWAhx5R_yA_142["T"]
  n_I3o6vIBZrQdWAhx5R_yA_143["F"]
  n_I3o6vIBZrQdWAhx5R_yA_144["T"]
  n_I3o6vIBZrQdWAhx5R_yA_145["F"]
  n_I3o6vIBZrQdWAhx5R_yA_146["T"]
  n_I3o6vIBZrQdWAhx5R_yA_147["F"]
  n_I3o6vIBZrQdWAhx5R_yA_148["T"]
  n_I3o6vIBZrQdWAhx5R_yA_149["F"]
  n_I3o6vIBZrQdWAhx5R_yA_150["T"]
  n_I3o6vIBZrQdWAhx5R_yA_151["F"]
  n_I3o6vIBZrQdWAhx5R_yA_152["T"]
  n_I3o6vIBZrQdWAhx5R_yA_153["F"]
  n_I3o6vIBZrQdWAhx5R_yA_154["T"]
  n_I3o6vIBZrQdWAhx5R_yA_155["F"]
  n_I3o6vIBZrQdWAhx5R_yA_156["T"]
  n_I3o6vIBZrQdWAhx5R_yA_157["F"]
  n_I3o6vIBZrQdWAhx5R_yA_158["T"]
  n_I3o6vIBZrQdWAhx5R_yA_159["F"]
  n_I3o6vIBZrQdWAhx5R_yA_16["out_sel = 1"]
  n_I3o6vIBZrQdWAhx5R_yA_160["T"]
  n_I3o6vIBZrQdWAhx5R_yA_161["F"]
  n_I3o6vIBZrQdWAhx5R_yA_162["T"]
  n_I3o6vIBZrQdWAhx5R_yA_163["F"]
  n_I3o6vIBZrQdWAhx5R_yA_164["T"]
  n_I3o6vIBZrQdWAhx5R_yA_165["F"]
  n_I3o6vIBZrQdWAhx5R_yA_166["T"]
  n_I3o6vIBZrQdWAhx5R_yA_167["F"]
  n_I3o6vIBZrQdWAhx5R_yA_168["T"]
  n_I3o6vIBZrQdWAhx5R_yA_169["F"]
  n_I3o6vIBZrQdWAhx5R_yA_170["T"]
  n_I3o6vIBZrQdWAhx5R_yA_171["F"]
  n_I3o6vIBZrQdWAhx5R_yA_18["tick_cnt > 19000"]
  n_I3o6vIBZrQdWAhx5R_yA_2["START"]
  n_I3o6vIBZrQdWAhx5R_yA_20["dht11 = 1"]
  n_I3o6vIBZrQdWAhx5R_yA_28["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_29["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_3["WAIT"]
  n_I3o6vIBZrQdWAhx5R_yA_31["tick_cnt > 30"]
  n_I3o6vIBZrQdWAhx5R_yA_42["SYNCL"]
  n_I3o6vIBZrQdWAhx5R_yA_43["SYNCH"]
  n_I3o6vIBZrQdWAhx5R_yA_44["out_sel = 0"]
  n_I3o6vIBZrQdWAhx5R_yA_46["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_48["tick_cnt > 40 && dht11_sync2 == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_50["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_58["DATA_SYNC"]
  n_I3o6vIBZrQdWAhx5R_yA_59["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_6["dht11 = 1"]
  n_I3o6vIBZrQdWAhx5R_yA_61["tick_cnt > 40 && dht11_sync2 == ０"]
  n_I3o6vIBZrQdWAhx5R_yA_63["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_71["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_74["dht11_sync2 == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_76["DATA_COUNT"]
  n_I3o6vIBZrQdWAhx5R_yA_8["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_80["tick_cnt + 1"]
  n_I3o6vIBZrQdWAhx5R_yA_84["DATA_DECISION"]
  n_I3o6vIBZrQdWAhx5R_yA_85["STOP"]
  n_I3o6vIBZrQdWAhx5R_yA_91["tick_cnt > 50"]
  n_I3o6vIBZrQdWAhx5R_yA_95["tick_us == 1"]
  n_I3o6vIBZrQdWAhx5R_yA_97["tick_cnt > 50"]
  n_I3o6vIBZrQdWAhx5R_yA_99["tick_cnt + 1"]
  n_LHpnPW8tvNSS5xcZV_IS_134["IDLEdht11 = 1out_sel = 1"]
  n_LHpnPW8tvNSS5xcZV_IS_135["STARTdht11 = 0"]
  n_LHpnPW8tvNSS5xcZV_IS_136["WAITdht11 = 1"]
  n_LHpnPW8tvNSS5xcZV_IS_137["SYNCLout_sel = 0"]
  n_LHpnPW8tvNSS5xcZV_IS_138["SYNCH"]
  n_LHpnPW8tvNSS5xcZV_IS_139["DATA_SYNC"]
  n_LHpnPW8tvNSS5xcZV_IS_140["DATA_COUNT"]
  n_LHpnPW8tvNSS5xcZV_IS_141["DATA_DECISIONdht11 = 0"]
  n_LHpnPW8tvNSS5xcZV_IS_142["STOP"]
  n_LHpnPW8tvNSS5xcZV_IS_144["start == 1"]
  n_LHpnPW8tvNSS5xcZV_IS_146["19msec"]
  n_LHpnPW8tvNSS5xcZV_IS_148["30usec"]
  n_LHpnPW8tvNSS5xcZV_IS_150["40usec && dht11 == 1"]
  n_LHpnPW8tvNSS5xcZV_IS_152["dht11 == 1"]
  n_LHpnPW8tvNSS5xcZV_IS_154["dht11 == 0"]
  n_LHpnPW8tvNSS5xcZV_IS_156["bit_cnt == 39"]
  n_LHpnPW8tvNSS5xcZV_IS_158["50usec"]
  n_LHpnPW8tvNSS5xcZV_IS_160["40usec && dht11 == 0"]
  n_LHpnPW8tvNSS5xcZV_IS_162["bit_cnt < 40"]
  n_Vi__6CvgpSDGO70bpXuD_5["ASM 가로 버전"]
  n_Vi__6CvgpSDGO70bpXuD_6["ASM 세로 버전"]
  n_Z81LdokMab6rXbbP6AQJ_1["tick_us == 1"]
  n_Z81LdokMab6rXbbP6AQJ_12["bit = 1 저장<br/>tick_cnt = 0"]
  n_Z81LdokMab6rXbbP6AQJ_13["bit_cnt + 1"]
  n_Z81LdokMab6rXbbP6AQJ_14["bit = 0 저장<br/>tick_cnt = 0"]
  n_Z81LdokMab6rXbbP6AQJ_19["bit_cnt == 39"]
  n_Z81LdokMab6rXbbP6AQJ_4["dht11_sync2 == 0"]
  n_Z81LdokMab6rXbbP6AQJ_6["tick_cnt + 1"]
  n_3f0HE_8pnrwOXLfxls7N_6 --> n_1xamawp9gnZpQtRdpWja_1
  n_I3o6vIBZrQdWAhx5R_yA_6 --> n_I3o6vIBZrQdWAhx5R_yA_16
  n_LHpnPW8tvNSS5xcZV_IS_134 --> n_LHpnPW8tvNSS5xcZV_IS_135
