flowchart LR
  n_7zgxCeO7lLHFsRtG4hqR_1["out[7:0]"]
  n_7zgxCeO7lLHFsRtG4hqR_10["dedicated_cpu_vif"]
  n_7zgxCeO7lLHFsRtG4hqR_12["dedicated_cpu_if"]
  n_7zgxCeO7lLHFsRtG4hqR_14["monitor"]
  n_7zgxCeO7lLHFsRtG4hqR_15["transaction"]
  n_7zgxCeO7lLHFsRtG4hqR_17["event_gen_next"]
  n_7zgxCeO7lLHFsRtG4hqR_18["scoreboard"]
  n_7zgxCeO7lLHFsRtG4hqR_19["transaction"]
  n_7zgxCeO7lLHFsRtG4hqR_21["mailbox"]
  n_7zgxCeO7lLHFsRtG4hqR_24["event_drv_ready"]
  n_7zgxCeO7lLHFsRtG4hqR_25["dut"]
  n_7zgxCeO7lLHFsRtG4hqR_3["Dedicated CPU"]
  n_7zgxCeO7lLHFsRtG4hqR_4["generator"]
  n_7zgxCeO7lLHFsRtG4hqR_6["transaction"]
  n_7zgxCeO7lLHFsRtG4hqR_8["mailbox"]
  n_7zgxCeO7lLHFsRtG4hqR_9["driver"]
  n__AtSrzDVrfFM_dhdxfO6_105["count_is_last"]
  n__AtSrzDVrfFM_dhdxfO6_112["clk"]
  n__AtSrzDVrfFM_dhdxfO6_114["rst"]
  n__AtSrzDVrfFM_dhdxfO6_173["node_O6-173"]
  n__AtSrzDVrfFM_dhdxfO6_174["node_O6-174"]
  n__AtSrzDVrfFM_dhdxfO6_175["node_O6-175"]
  n__AtSrzDVrfFM_dhdxfO6_176["a_src_sel"]
  n__AtSrzDVrfFM_dhdxfO6_177["sum_src_cel"]
  n__AtSrzDVrfFM_dhdxfO6_178["a_reg_load"]
  n__AtSrzDVrfFM_dhdxfO6_179["sum_reg_load"]
  n__AtSrzDVrfFM_dhdxfO6_180["out_reg_load"]
  n__AtSrzDVrfFM_dhdxfO6_181["alu_src_sel"]
  n__AtSrzDVrfFM_dhdxfO6_182["node_O6-182"]
  n__AtSrzDVrfFM_dhdxfO6_183["S0"]
  n__AtSrzDVrfFM_dhdxfO6_184["0"]
  n__AtSrzDVrfFM_dhdxfO6_185["0"]
  n__AtSrzDVrfFM_dhdxfO6_186["1"]
  n__AtSrzDVrfFM_dhdxfO6_187["1"]
  n__AtSrzDVrfFM_dhdxfO6_188["0"]
  n__AtSrzDVrfFM_dhdxfO6_189["X"]
  n__AtSrzDVrfFM_dhdxfO6_190["node_O6-190"]
  n__AtSrzDVrfFM_dhdxfO6_191["S1"]
  n__AtSrzDVrfFM_dhdxfO6_192["X"]
  n__AtSrzDVrfFM_dhdxfO6_193["X"]
  n__AtSrzDVrfFM_dhdxfO6_194["0"]
  n__AtSrzDVrfFM_dhdxfO6_195["0"]
  n__AtSrzDVrfFM_dhdxfO6_196["0"]
  n__AtSrzDVrfFM_dhdxfO6_197["X"]
  n__AtSrzDVrfFM_dhdxfO6_198["node_O6-198"]
  n__AtSrzDVrfFM_dhdxfO6_199["S2"]
  n__AtSrzDVrfFM_dhdxfO6_200["X"]
  n__AtSrzDVrfFM_dhdxfO6_201["X"]
  n__AtSrzDVrfFM_dhdxfO6_202["0"]
  n__AtSrzDVrfFM_dhdxfO6_203["0"]
  n__AtSrzDVrfFM_dhdxfO6_204["1"]
  n__AtSrzDVrfFM_dhdxfO6_205["X"]
  n__AtSrzDVrfFM_dhdxfO6_206["node_O6-206"]
  n__AtSrzDVrfFM_dhdxfO6_207["S5"]
  n__AtSrzDVrfFM_dhdxfO6_208["X"]
  n__AtSrzDVrfFM_dhdxfO6_209["X"]
  n__AtSrzDVrfFM_dhdxfO6_210["0"]
  n__AtSrzDVrfFM_dhdxfO6_211["0"]
  n__AtSrzDVrfFM_dhdxfO6_212["1"]
  n__AtSrzDVrfFM_dhdxfO6_213["X"]
  n__AtSrzDVrfFM_dhdxfO6_214["node_O6-214"]
  n__AtSrzDVrfFM_dhdxfO6_215["S3"]
  n__AtSrzDVrfFM_dhdxfO6_216["1"]
  n__AtSrzDVrfFM_dhdxfO6_217["X"]
  n__AtSrzDVrfFM_dhdxfO6_218["1"]
  n__AtSrzDVrfFM_dhdxfO6_219["0"]
  n__AtSrzDVrfFM_dhdxfO6_220["0"]
  n__AtSrzDVrfFM_dhdxfO6_221["0"]
  n__AtSrzDVrfFM_dhdxfO6_223["node_O6-223"]
  n__AtSrzDVrfFM_dhdxfO6_224["S4"]
  n__AtSrzDVrfFM_dhdxfO6_225["X"]
  n__AtSrzDVrfFM_dhdxfO6_226["1"]
  n__AtSrzDVrfFM_dhdxfO6_227["0"]
  n__AtSrzDVrfFM_dhdxfO6_228["1"]
  n__AtSrzDVrfFM_dhdxfO6_229["0"]
  n__AtSrzDVrfFM_dhdxfO6_230["1"]
  n__AtSrzDVrfFM_dhdxfO6_232["앞으로는 아래와 같이 Trues Table로 미리 값을 정의해놔야함."]
  n__AtSrzDVrfFM_dhdxfO6_84["cpu_sum_1to10_55"]
  n__AtSrzDVrfFM_dhdxfO6_85["datapath"]
  n__AtSrzDVrfFM_dhdxfO6_87["control_unit"]
  n__AtSrzDVrfFM_dhdxfO6_88["data storage"]
  n_7zgxCeO7lLHFsRtG4hqR_4 --> n_7zgxCeO7lLHFsRtG4hqR_8
  n_7zgxCeO7lLHFsRtG4hqR_8 --> n_7zgxCeO7lLHFsRtG4hqR_9
  n_7zgxCeO7lLHFsRtG4hqR_12 --> n_7zgxCeO7lLHFsRtG4hqR_25
  n_7zgxCeO7lLHFsRtG4hqR_14 --> n_7zgxCeO7lLHFsRtG4hqR_21
  n_7zgxCeO7lLHFsRtG4hqR_18 --> n_7zgxCeO7lLHFsRtG4hqR_4
  n_7zgxCeO7lLHFsRtG4hqR_21 --> n_7zgxCeO7lLHFsRtG4hqR_18
